receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:

  debug:

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlphttp/newrelic:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      api-key: 729fc62b5caa51033b4695151e3213e4d085NRAL

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, otlphttp/newrelic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/newrelic]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/newrelic]