spring.application.name=db-service

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/fooddb
spring.datasource.username=postgres
spring.datasource.password=postgres

management.endpoints.web.exposure.include=*

management.metrics.export.prometheus.enabled=true

logging.pattern.level=%5p [${spring.application.name:},traceId=%X{trace_id},spanId=%X{span_id}]
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.95